<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ApplicationHangWatchdog</AssemblyName>
    <RootNamespace>ApplicationHangWatchdog</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.1.2</Version>
    <FileVersion>1.1.2.0</FileVersion>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
  </PropertyGroup>
</Project>
